### ISSUE TITLE
undefined method 'link_to'

### ISSUE THREAD

**Issue by aussiDavid** [capistrano/maintenance#33]
```
$ cap staging maintenance:enable REASON="Testing" --trace

** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
Using airbrussh format.
Verbose output is being written to log/capistrano.log.
** Invoke bundler:map_bins (first_time)
** Invoke passenger:bundler:hook (first_time)
** Execute passenger:bundler:hook
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_rails_env
** Invoke rvm:hook (first_time)
** Invoke passenger:rvm:hook (first_time)
** Invoke passenger:test_which_passenger (first_time)
** Execute passenger:test_which_passenger
** Execute passenger:rvm:hook
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.2.3
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
** Invoke maintenance:enable (first_time)
** Execute maintenance:enable
cap aborted!
NoMethodError: undefined method `link_to' for #<SSHKit::Backend::Netssh:0x007fb84ac6c870>
(erb):8:in `block (3 levels) in <top (required)>'
/Users/David/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `eval'
/Users/David/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `result'
/Users/David/.rvm/gems/ruby-2.2.3/gems/capistrano-maintenance-1.0.0/lib/capistrano/tasks/maintenance.rake:12:in `block (3 levels) in <top (required)>'
/Users/David/.rvm/gems/ruby-2.2.3/gems/sshkit-1.11.3/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/David/.rvm/gems/ruby-2.2.3/gems/sshkit-1.11.3/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/David/.rvm/gems/ruby-2.2.3/gems/sshkit-1.11.3/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => maintenance:enable
```

**Comment by aussiDavid** [comment]
I just realised this is because I'm using rails operations (i.e. `link_to`) in an environment that most likely hasn't included it.

Is there a way to set up the maintenance template such that it can use the apps functions such as render, link_to, and maybe helper functions?

**Comment by mattbrictson** [comment]
No, I don't think this is possible. That would involve loading your entire Rails app inside Capistrano, which is something I've never seen done. Not to mention that Capistrano is used for deploying many types of non-Rails projects (e.g. PHP apps), and so requiring Rails helpers in a general purpose tool is not reasonable.

If you figure out a way to do it, I would accept a PR that adds an explanation of your technique to the README, but I wouldn't want to make changes to the gem itself.

**Comment by aussiDavid** [comment]
fair enough, Thanks.
