### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by imidsac** [capistrano/maintenance#39]
```
[ 2017-02-11 12:15:39.0290 18902/7fd425450700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/tarbiyah/staging/current: An error occurred while starting up the preloader.
  Error ID: 46d1c008
  Error details saved to: /tmp/passenger-error-d43sGk.html
  Message from application: undefined method `namespace' for main:Object (NoMethodError)
  /var/www/tarbiyah/staging/shared/bundle/ruby/2.3.0/gems/capistrano-maintenance-1.1.0/lib/capistrano/tasks/maintenance.rake:1:in `<top (required)>'
  /var/www/tarbiyah/staging/shared/bundle/ruby/2.3.0/gems/capistrano-maintenance-1.1.0/lib/capistrano/maintenance.rb:1:in `load'
  /var/www/tarbiyah/staging/shared/bundle/ruby/2.3.0/gems/capistrano-maintenance-1.1.0/lib/capistrano/maintenance.rb:1:in `<top (required)>'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/runtime.rb:105:in `require'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/runtime.rb:105:in `rescue in block in require'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/runtime.rb:82:in `block in require'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
  /home/imidsac/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
  /var/www/tarbiyah/staging/releases/20170211120631/config/application.rb:7:in `<top (required)>'
  /var/www/tarbiyah/staging/releases/20170211120631/config/environment.rb:2:in `require_relative'
  /var/www/tarbiyah/staging/releases/20170211120631/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /var/www/tarbiyah/staging/shared/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/tarbiyah/staging/shared/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by hajder** [comment]
@imidsac I encountered the same error just now, what was your solution?

**Comment by imidsac** [comment]
Hi
Sorry for being late......
I simply add ```require: false``` in Gemfile.
